// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mostlylucid.SegmentCommerce.Data;
using Mostlylucid.SegmentCommerce.Data.Entities;
using Mostlylucid.SegmentCommerce.Data.Entities.Profiles;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Mostlylucid.SegmentCommerce.Migrations
{
    [DbContext(typeof(SegmentCommerceDbContext))]
    [Migration("20251229150722_UP_12")]
    partial class UP_12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CssClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("css_class");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.DemoUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avatar_color");

                    b.Property<Dictionary<string, double>>("BrandAffinities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("brand_affinities");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, double>>("Interests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("persona");

                    b.Property<List<string>>("PreferredTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_tags");

                    b.Property<decimal?>("PriceMax")
                        .HasColumnType("numeric")
                        .HasColumnName("price_max");

                    b.Property<decimal?>("PriceMin")
                        .HasColumnType("numeric")
                        .HasColumnName("price_min");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<long>("Segments")
                        .HasColumnType("bigint")
                        .HasColumnName("segments");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SortOrder");

                    b.ToTable("demo_users");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.InteractionEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Category", "CreatedAt");

                    b.ToTable("interaction_events");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.InterestEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ProfileId");

                    b.ToTable("interest_embeddings");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.JobQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("queue");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.ToTable("job_queue");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_hash");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<int>("FulfillmentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("fulfillment_status");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("SessionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_key");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("ShippingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_country");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shipping_method");

                    b.Property<string>("ShippingRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.HasIndex("SessionKey");

                    b.HasIndex("Status");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("original_price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_image_url");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<int?>("VariationId")
                        .HasColumnType("integer")
                        .HasColumnName("variation_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariationId");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductEmbeddingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("product_embeddings");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryPath")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("category_path");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compare_at_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("handle");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trending");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("original_price");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subcategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subcategory");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CategoryPath");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryPath"), "gist");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsTrending");

                    b.HasIndex("SellerId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductTaxonomyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("TaxonomyNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("taxonomy_node_id");

                    b.HasKey("Id");

                    b.HasIndex("TaxonomyNodeId");

                    b.HasIndex("ProductId", "TaxonomyNodeId")
                        .IsUnique();

                    b.ToTable("product_taxonomy");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductVariationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("integer")
                        .HasColumnName("availability_status");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("compare_at_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Gtin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gtin");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("original_price");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Color");

                    b.HasIndex("ProductId");

                    b.HasIndex("Size");

                    b.HasIndex("ProductId", "Color", "Size")
                        .IsUnique();

                    b.ToTable("product_variations");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.PersistentProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, double>>("Affinities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("affinities");

                    b.Property<Dictionary<string, double>>("BrandAffinities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("brand_affinities");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<DateTime?>("EmbeddingComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("embedding_computed_at");

                    b.Property<int>("IdentificationMode")
                        .HasColumnType("integer")
                        .HasColumnName("identification_mode");

                    b.Property<Dictionary<string, double>>("Interests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interests");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Dictionary<string, double>>("LlmSegments")
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_segments");

                    b.Property<PricePreferences>("PricePreferences")
                        .HasColumnType("jsonb")
                        .HasColumnName("price_preferences");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("profile_key");

                    b.Property<long>("Segments")
                        .HasColumnType("bigint")
                        .HasColumnName("segments");

                    b.Property<DateTime?>("SegmentsComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("segments_computed_at");

                    b.Property<int>("TotalCartAdds")
                        .HasColumnType("integer")
                        .HasColumnName("total_cart_adds");

                    b.Property<int>("TotalPurchases")
                        .HasColumnType("integer")
                        .HasColumnName("total_purchases");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer")
                        .HasColumnName("total_sessions");

                    b.Property<int>("TotalSignals")
                        .HasColumnType("integer")
                        .HasColumnName("total_signals");

                    b.Property<Dictionary<string, bool>>("Traits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("traits");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Affinities");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Affinities"), "gin");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("IdentificationMode");

                    b.HasIndex("Interests");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Interests"), "gin");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("LlmSegments");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LlmSegments"), "gin");

                    b.HasIndex("ProfileKey")
                        .IsUnique();

                    b.HasIndex("Segments");

                    b.ToTable("persistent_profiles");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.ProfileKeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("KeyType")
                        .HasColumnType("integer")
                        .HasColumnName("key_type");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key_value");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("KeyValue", "KeyType")
                        .IsUnique();

                    b.ToTable("profile_keys");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.SignalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("page_url");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signal_type");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SignalType");

                    b.ToTable("signals");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.SellerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sellers");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("stores");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId", "ProductId")
                        .IsUnique();

                    b.ToTable("store_products");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "UserId")
                        .IsUnique();

                    b.ToTable("store_users");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyNodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<string>("ShopifyTaxonomyId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shopify_taxonomy_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("ShopifyTaxonomyId")
                        .IsUnique();

                    b.ToTable("taxonomy_nodes");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.VisitorProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Dictionary<string, InterestWeightData>>("Interests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interests");

                    b.Property<bool>("IsUnmasked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unmasked");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("ProfileToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_token");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("integer")
                        .HasColumnName("total_visits");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("ProfileToken")
                        .IsUnique();

                    b.ToTable("visitor_profiles");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.DemoUserEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.PersistentProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.InteractionEventEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.VisitorProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.OwnsOne("Mostlylucid.SegmentCommerce.Data.Entities.InteractionMetadata", "Metadata", b1 =>
                        {
                            b1.Property<long>("InteractionEventEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("DeviceType")
                                .HasColumnType("text");

                            b1.Property<int?>("Position")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("Price")
                                .HasColumnType("numeric");

                            b1.Property<int?>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<int?>("ScrollDepth")
                                .HasColumnType("integer");

                            b1.Property<string>("SearchQuery")
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .HasColumnType("text");

                            b1.Property<int?>("TimeOnPageSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("VariantInfo")
                                .HasColumnType("text");

                            b1.Property<int?>("ViewportHeight")
                                .HasColumnType("integer");

                            b1.Property<int?>("ViewportWidth")
                                .HasColumnType("integer");

                            b1.HasKey("InteractionEventEntityId");

                            b1.ToTable("interaction_events");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("InteractionEventEntityId");
                        });

                    b.Navigation("Metadata");

                    b.Navigation("Product");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.InterestEmbeddingEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.VisitorProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OrderEntity", b =>
                {
                    b.OwnsOne("Mostlylucid.SegmentCommerce.Data.Entities.OrderMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("OrderEntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("AffiliateCode")
                                .HasColumnType("text");

                            b1.Property<string>("CouponCode")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNotes")
                                .HasColumnType("text");

                            b1.Property<string>("DeviceType")
                                .HasColumnType("text");

                            b1.Property<string>("GiftMessage")
                                .HasColumnType("text");

                            b1.Property<bool>("IsGift")
                                .HasColumnType("boolean");

                            b1.Property<string>("UserAgent")
                                .HasColumnType("text");

                            b1.Property<string>("UtmCampaign")
                                .HasColumnType("text");

                            b1.Property<string>("UtmMedium")
                                .HasColumnType("text");

                            b1.Property<string>("UtmSource")
                                .HasColumnType("text");

                            b1.HasKey("OrderEntityId");

                            b1.ToTable("orders");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("OrderEntityId");
                        });

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductVariationEntity", "Variation")
                        .WithMany()
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductEmbeddingEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.SellerEntity", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductTaxonomyEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany("ProductTaxonomy")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyNodeEntity", "TaxonomyNode")
                        .WithMany("ProductTaxonomy")
                        .HasForeignKey("TaxonomyNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TaxonomyNode");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductVariationEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.ProfileKeyEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.PersistentProfileEntity", "Profile")
                        .WithMany("AlternateKeys")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.SignalEntity", b =>
                {
                    b.OwnsOne("Mostlylucid.SegmentCommerce.Data.Entities.SignalContext", "Context", b1 =>
                        {
                            b1.Property<long>("SignalEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AppliedFilters")
                                .HasColumnType("text");

                            b1.Property<int?>("ClickCount")
                                .HasColumnType("integer");

                            b1.Property<bool>("ComparedProducts")
                                .HasColumnType("boolean");

                            b1.Property<string>("DeviceType")
                                .HasColumnType("text");

                            b1.Property<int?>("HoverDurationMs")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("PricePoint")
                                .HasColumnType("numeric");

                            b1.Property<int?>("ScrollDepth")
                                .HasColumnType("integer");

                            b1.Property<string>("SearchQuery")
                                .HasColumnType("text");

                            b1.Property<int?>("TimeOnPageSeconds")
                                .HasColumnType("integer");

                            b1.Property<bool>("ViewedImages")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ViewedReviews")
                                .HasColumnType("boolean");

                            b1.HasKey("SignalEntityId");

                            b1.ToTable("signals");

                            b1.ToJson("Context");

                            b1.WithOwner()
                                .HasForeignKey("SignalEntityId");
                        });

                    b.Navigation("Context");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreProductEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", "Product")
                        .WithMany("StoreProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.StoreEntity", "Store")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreUserEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.StoreEntity", "Store")
                        .WithMany("StoreUsers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyNodeEntity", b =>
                {
                    b.HasOne("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyNodeEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyAttributes", "Attributes", b1 =>
                        {
                            b1.Property<int>("TaxonomyNodeEntityId")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("AveragePricePoint")
                                .HasColumnType("numeric");

                            b1.Property<string>("BannerImageUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<string>("Icon")
                                .HasColumnType("text");

                            b1.Property<bool>("IsFeatured")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsSeasonal")
                                .HasColumnType("boolean");

                            b1.Property<string>("MetaDescription")
                                .HasColumnType("text");

                            b1.Property<string>("MetaKeywords")
                                .HasColumnType("text");

                            b1.Property<string>("Season")
                                .HasColumnType("text");

                            b1.Property<string>("TargetDemographic")
                                .HasColumnType("text");

                            b1.HasKey("TaxonomyNodeEntityId");

                            b1.ToTable("taxonomy_nodes");

                            b1.ToJson("Attributes");

                            b1.WithOwner()
                                .HasForeignKey("TaxonomyNodeEntityId");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductTaxonomy");

                    b.Navigation("StoreProducts");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.Profiles.PersistentProfileEntity", b =>
                {
                    b.Navigation("AlternateKeys");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.SellerEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.StoreEntity", b =>
                {
                    b.Navigation("StoreProducts");

                    b.Navigation("StoreUsers");
                });

            modelBuilder.Entity("Mostlylucid.SegmentCommerce.Data.Entities.TaxonomyNodeEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductTaxonomy");
                });
#pragma warning restore 612, 618
        }
    }
}
