using System.Text.Json.Serialization;

namespace Mostlylucid.SegmentCommerce.SampleData.Models;

/// <summary>
/// A product definition generated by Ollama.
/// </summary>
public class GeneratedProduct
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    [JsonPropertyName("price")]
    public decimal Price { get; set; }

    [JsonPropertyName("original_price")]
    public decimal? OriginalPrice { get; set; }

    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; } = [];

    [JsonPropertyName("is_trending")]
    public bool IsTrending { get; set; }

    [JsonPropertyName("is_featured")]
    public bool IsFeatured { get; set; }

    [JsonPropertyName("image_prompt")]
    public string ImagePrompt { get; set; } = string.Empty;

    [JsonPropertyName("colour_variants")]
    public List<string> ColourVariants { get; set; } = [];

    /// <summary>
    /// Generated image paths (filled after ComfyUI generation).
    /// </summary>
    public List<GeneratedImage> Images { get; set; } = [];
}

public class GeneratedImage
{
    public string FilePath { get; set; } = string.Empty;
    public string Variant { get; set; } = string.Empty; // "main", "angle_1", "colour_black", etc.
    public bool IsPrimary { get; set; }
}

/// <summary>
/// Batch of products for a category.
/// </summary>
public class CategoryProductBatch
{
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    [JsonPropertyName("products")]
    public List<GeneratedProduct> Products { get; set; } = [];
}

/// <summary>
/// Configuration for product generation.
/// </summary>
public record GenerationConfig
{
    public string OllamaBaseUrl { get; init; } = "http://localhost:11434";
    public string OllamaModel { get; init; } = "llama3.2";
    public int OllamaTimeoutSeconds { get; init; } = 120;

    public string ComfyUIBaseUrl { get; init; } = "http://localhost:8188";
    public string OutputPath { get; init; } = "./Output/images";
    public int ComfyUITimeoutSeconds { get; init; } = 300;

    public int ProductsPerCategory { get; init; } = 10;
    public int ImagesPerProduct { get; init; } = 3;
    public int ImageWidth { get; init; } = 512;
    public int ImageHeight { get; init; } = 512;

    public string ConnectionString { get; init; } = string.Empty;
}

/// <summary>
/// Categories available for generation.
/// </summary>
public static class ProductCategories
{
    public static readonly Dictionary<string, CategoryDefinition> All = new()
    {
        ["tech"] = new CategoryDefinition
        {
            Slug = "tech",
            DisplayName = "Technology",
            Description = "Consumer electronics, gadgets, computer peripherals, smart devices",
            ExampleProducts = "wireless headphones, mechanical keyboards, webcams, portable SSDs, smart speakers, fitness trackers",
            PriceRange = (29.99m, 499.99m)
        },
        ["fashion"] = new CategoryDefinition
        {
            Slug = "fashion",
            DisplayName = "Fashion",
            Description = "Clothing, accessories, footwear, jewellery",
            ExampleProducts = "leather jackets, designer sunglasses, minimalist watches, premium t-shirts, sneakers",
            PriceRange = (19.99m, 399.99m)
        },
        ["home"] = new CategoryDefinition
        {
            Slug = "home",
            DisplayName = "Home & Garden",
            Description = "Home decor, furniture, kitchen items, garden supplies, smart home devices",
            ExampleProducts = "smart LED bulbs, ergonomic chairs, indoor plants, diffusers, kitchen gadgets",
            PriceRange = (14.99m, 599.99m)
        },
        ["sport"] = new CategoryDefinition
        {
            Slug = "sport",
            DisplayName = "Sports & Fitness",
            Description = "Exercise equipment, sportswear, outdoor gear, fitness accessories",
            ExampleProducts = "running shoes, yoga mats, resistance bands, fitness trackers, water bottles",
            PriceRange = (9.99m, 249.99m)
        },
        ["books"] = new CategoryDefinition
        {
            Slug = "books",
            DisplayName = "Books",
            Description = "Fiction, non-fiction, technical books, audiobooks, e-readers",
            ExampleProducts = "programming books, self-help books, novels, business books, cookbooks",
            PriceRange = (9.99m, 59.99m)
        },
        ["food"] = new CategoryDefinition
        {
            Slug = "food",
            DisplayName = "Food & Drink",
            Description = "Gourmet food, beverages, cooking ingredients, specialty items",
            ExampleProducts = "artisan coffee, gourmet chocolate, olive oil, specialty teas, snack boxes",
            PriceRange = (9.99m, 79.99m)
        }
    };
}

public class CategoryDefinition
{
    public string Slug { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string ExampleProducts { get; set; } = string.Empty;
    public (decimal Min, decimal Max) PriceRange { get; set; }
}
