namespace Mostlylucid.CsvLlm.Models;

/// <summary>
/// Complete profile of a tabular data source
/// </summary>
public class DataProfile
{
    public string SourcePath { get; set; } = "";
    public string SourceType { get; set; } = ""; // csv, xlsx, parquet
    public long RowCount { get; set; }
    public List<ColumnProfile> Columns { get; set; } = new();
    public List<DataAlert> Alerts { get; set; } = new();
    public List<ColumnCorrelation> Correlations { get; set; } = new();
    public List<DataInsight> Insights { get; set; } = new();
    public TimeSpan ProfileTime { get; set; }
}

/// <summary>
/// Statistical profile for a single column
/// </summary>
public class ColumnProfile
{
    public string Name { get; set; } = "";
    public string DuckDbType { get; set; } = "";
    public ColumnType InferredType { get; set; }
    
    // Counts
    public long Count { get; set; }
    public long NullCount { get; set; }
    public long UniqueCount { get; set; }
    public double NullPercent => Count > 0 ? (NullCount * 100.0 / Count) : 0;
    public double UniquePercent => Count > 0 ? (UniqueCount * 100.0 / Count) : 0;
    
    // Numeric stats (null if not numeric)
    public double? Min { get; set; }
    public double? Max { get; set; }
    public double? Mean { get; set; }
    public double? Median { get; set; }
    public double? StdDev { get; set; }
    public double? Q25 { get; set; }
    public double? Q75 { get; set; }
    public double? Skewness { get; set; }
    
    // Categorical stats
    public List<ValueCount>? TopValues { get; set; }
    public double? ImbalanceRatio { get; set; } // Top value % / expected %
    
    // Date stats
    public DateTime? MinDate { get; set; }
    public DateTime? MaxDate { get; set; }
    public TimeSpan? DateRange { get; set; }
}

public enum ColumnType
{
    Unknown,
    Numeric,
    Categorical,
    DateTime,
    Text,
    Boolean
}

public class ValueCount
{
    public string Value { get; set; } = "";
    public long Count { get; set; }
    public double Percent { get; set; }
}

/// <summary>
/// Data quality alert
/// </summary>
public class DataAlert
{
    public AlertSeverity Severity { get; set; }
    public string Column { get; set; } = "";
    public AlertType Type { get; set; }
    public string Message { get; set; } = "";
}

public enum AlertSeverity { Info, Warning, Error }

public enum AlertType
{
    HighNulls,          // >10% nulls
    HighCardinality,    // Unique values > 90% (probably ID)
    LowCardinality,     // <5 unique values (maybe should be categorical)
    Constant,           // Only 1 unique value
    HighSkewness,       // |skewness| > 2
    Outliers,           // Values beyond 3*IQR
    Imbalanced,         // Top category > 80%
    MixedTypes,         // Column has mixed data types
    PossibleId,         // Sequential integers or UUIDs
    DateGaps            // Missing dates in time series
}

/// <summary>
/// Correlation between two columns
/// </summary>
public class ColumnCorrelation
{
    public string Column1 { get; set; } = "";
    public string Column2 { get; set; } = "";
    public double Correlation { get; set; }
    public string Strength => Math.Abs(Correlation) switch
    {
        >= 0.8 => "Very Strong",
        >= 0.6 => "Strong",
        >= 0.4 => "Moderate",
        >= 0.2 => "Weak",
        _ => "None"
    };
}

/// <summary>
/// An insight derived from the data (from LLM or heuristics)
/// </summary>
public class DataInsight
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public string? Sql { get; set; }
    public InsightSource Source { get; set; }
    public List<string> RelatedColumns { get; set; } = new();
}

public enum InsightSource
{
    Statistical,    // Derived from stats (no LLM)
    LlmGenerated    // Generated by LLM query
}
